GET http://localhost:8080/users

################################
POST http://localhost:8080/users
content-type: application/json

{
    "email": "taipv2s2@gmail.com",
    "password" :"123"
}
#########################
POST http://localhost:8080/users/login 
Content-Type: application/json

{
    "email": "taipv@gmail.com",
    "password" :"123"
}
#########################
DELETE http://localhost:8080/users

